# Generated by Django 5.2.5 on 2025-08-17 22:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_client_restorateur_remove_emprunt_eleve_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plat',
            name='commande',
        ),
        migrations.AddField(
            model_name='plat',
            name='quantite_en_stock',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='LigneDePanier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.IntegerField(default=1)),
                ('panier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.panier')),
                ('plat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.plat')),
            ],
        ),
    ]
