# Generated by Django 5.2.5 on 2025-08-17 22:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_plat_commande_plat_quantite_en_stock_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='restorateur',
            new_name='Restaurateur',
        ),
        migrations.AddField(
            model_name='plat',
            name='restaurateur',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.restaurateur'),
        ),
        migrations.CreateModel(
            name='LigneDeCommande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.IntegerField(default=1)),
                ('prix', models.DecimalField(decimal_places=2, max_digits=6)),
                ('commande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.commande')),
                ('plat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.plat')),
            ],
        ),
    ]
